import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 18
[font.normal]
family = "VictorMono Nerd Font"
style = "Medium"
[font.bold]
family = "VictorMono Nerd Font"
style = "Bold"
[font.italic]
family = "VictorMono Nerd Font"
style = "Italic"
[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[window]
[window.padding]
x = 5
y = 5
[window.dimensions]
columns = 130
lines = 24
