#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

# First block.
[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

# Path segment for the CWD.
[[blocks.segments]]
type = 'path'
style = 'plain'
background = 'transparent'
foreground = 'blue'
template = '{{ .Path }}'

[blocks.segments.properties]
style = 'full'

# Git segment.
[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = 'p:grey'
background = 'transparent'
template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

[blocks.segments.properties]
branch_icon = ''
commit_icon = '@'
fetch_status = true

# Execution time and language info block.
[[blocks]]
alignment = 'right'
type = 'prompt'

# Node.
[[blocks.segments]]
type = 'node'
style = 'plain'
foreground = 'p:green'
background = 'transparent'
template = ' '

# Go.
[[blocks.segments]]
type = 'go'
style = 'plain'
foreground = 'p:blue'
background = 'transparent'
template = ' '

[blocks.segments.properties]
fetch_version = false

# Python.
[[blocks.segments]]
type = 'python'
style = 'plain'
foreground = 'p:yellow'
background = 'transparent'
template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ end }}'

[blocks.segments.properties]
display_mode = 'files'
fetch_version = false

# Execution time segment.
[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = 'yellow'
background = 'transparent'
template = '{{ .FormattedMs }}'

[blocks.segments.properties]
threshold = 5000

# Block for the user input.
[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}magenta{{end}}",
]
background = 'transparent'
template = '❯'

# Extras
[transient_prompt]
background = 'transparent'
foreground = 'magenta'
template = '❯ '

[secondary_prompt]
foreground = 'magenta'
background = 'transparent'
template = '❯❯ '

[palette]
grey = '#6c6c6c'
black = '#262B44'
blue = '#4B95E9'
green = '#59C9A5'
orange = '#F07623'
red = '#D81E5B'
white = '#E0DEF4'
yellow = '#F3AE35'
